---
title: "IEDSFB Week 4"
author: "Your Name Here"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r setup, include=FALSE}
  library(knitr)
  knitr::opts_chunk$set(echo = TRUE)
  opts_knit$set(root.dir=normalizePath('../'))
```

# Importing Data

## Download data to your machine

Last week you should have downloaded the data you need into the `input` folder. If not, run the following lines. Notice that this chunk is set to `eval=FALSE` so R will not download the data by default.

```{r download, eval=FALSE, warning=FALSE, message=FALSE}
  download.file("https://www.dropbox.com/s/k4d2j6feayezkun/r2d2.csv?dl=1", 
                destfile = "input/r2d2-w02.csv")
  download.file("https://www.dropbox.com/s/1e2tqqmfzmzaybe/r2d2.dta?dl=1", 
                destfile = "input/r2d2-w02.dta")
  download.file("https://www.dropbox.com/s/6b8t2c877yvqeax/r2d2.rds?dl=1", 
                destfile = "input/r2d2-w02.rds")
  download.file("https://www.dropbox.com/s/gwdp13x62u75m3s/r2d2.sas7bdat?dl=1", 
                destfile = "input/r2d2-w02.sas7bdat")
  download.file("https://www.dropbox.com/s/a8apx8h5f2n9dfq/r2d2.sav?dl=1", 
                destfile = "input/r2d2-w02.sav")
  download.file("https://www.dropbox.com/s/tiqgit23db2fk8x/r2d2.txt?dl=1", 
                destfile = "input/r2d2-w02.text")
  download.file("https://www.dropbox.com/s/7a3i7e0bfmqiikr/r2d2.xlsx?dl=1", 
                destfile = "input/r2d2-w02.xlsx")
```

```{r loadCSV}
  
```

```{r loadRDS}
  
```

```{r loadSTAT}
  
```

```{r loadXLSX}
  
```

```{r loadURL}
# a quick trick to check for the RCurl package and install if missing
  list.of.packages <- c("RCurl")
  new.packages <- list.of.packages[!(list.of.packages %in%
                                     installed.packages()[,"Package"])]
  if(length(new.packages)) install.packages(new.packages)
  
  library(RCurl)
  url <- getURL('https://docs.google.com/spreadsheets/d/e/2PACX-1vQLJfY4Hk0Uek5lLBxXrowCp-7XMP1_5Vze6grhUd5u_XcIlMzTkpwBG3sq0aZuzduNbpiv1oqPyd1w/pub?gid=1835311741&single=true&output=csv', 
                ssl.verifyhost=FALSE, ssl.verifypeer=FALSE)
  datURL <- read.csv(textConnection(url), header=T)
```

```{r loadJSON}
  source("https://tinyurl.com/y74jnzsc") # authentication code
  twitter_user <- "realDonaldTrump"
  url <- paste0("https://api.twitter.com/1.1/statuses/user_timeline.json?",
                "count=10&",
                "screen_name=", twitter_user)
  req <- httr::GET(url, httr::add_headers(Authorization = token))
  json <- httr::content(req, as = "text")
  tweets <- fromJSON(json)
  substring(tweets$text, 1, 100)
```

```{r str}

```

The `datCSV` data frame has ... observations (rows) and ... columns.

```{r glimpse}
# a quick trick to check for the tidyverse package and install if missing
  list.of.packages <- c("tidyverse")
  new.packages <- list.of.packages[!(list.of.packages %in%
                                     installed.packages()[,"Package"])]
  if(length(new.packages)) install.packages(new.packages)
  library(tidyverse)
  
```


```{r head}

```

```{r summary}

# what is the mean parent age (p.age.r1)?
```

```{r table}

# how many kids know how they were infected?
```

```{r missing}

# how many cases are missing data?
```

```{r logical}

# can you make a vector of parent age
```

```{r contingenecy}

# does the NA pattern make sense?
```

```{r proportions}
  
# what proportion of kids who know they are HIV postive also know
# how they were infected?
```

```{r plots}
  
```
